# Generated by Django 3.2.11 on 2022-01-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertvshow",
            name="last_watched",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
