# Generated by Django 3.2.11 on 2022-01-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_viewhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewhistory",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
