# Generated by Django 3.2.11 on 2022-01-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_viewhistory_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertvshow",
            old_name="user_profile",
            new_name="userprofile",
        ),
    ]
