# Generated by Django 3.2.11 on 2022-01-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingeauth", "0001_initial"),
        ("api", "0005_rename_user_profile_usertvshow_userprofile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertvshow",
            unique_together={("userprofile", "show")},
        ),
    ]
