# Generated by Django 3.2.11 on 2022-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_usertvshow_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="api_id",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="first_air_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="in_production",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="is_detailed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="number_of_episodes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="number_of_seasons",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="overview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="poster_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="vote_average",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="vote_count",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("api_id", "name")},
            },
        ),
        migrations.AddField(
            model_name="tvshow",
            name="genres",
            field=models.ManyToManyField(to="api.Genre"),
        ),
    ]
