# Generated by Django 3.2.11 on 2022-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20220123_2022"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viewhistory",
            options={"ordering": ["start_date"]},
        ),
        migrations.RemoveField(
            model_name="usertvshow",
            name="last_watched",
        ),
        migrations.RemoveField(
            model_name="usertvshow",
            name="times_watched",
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="start_date",
            field=models.DateField(),
        ),
    ]
