# Generated by Django 3.2.11 on 2022-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20220130_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertvshow",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="usertvshow",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__range", (0, 5))),
                name="api_usertvshow_rating_range",
            ),
        ),
    ]
