# Generated by Django 3.2.11 on 2022-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20220130_1753"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usertvshow",
            name="api_usertvshow_rating_range",
        ),
        migrations.AddConstraint(
            model_name="usertvshow",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__range", (0, 5))),
                name="api_usertvshow_rating_range",
            ),
        ),
    ]
