# Generated by Django 3.2.11 on 2022-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20220130_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvshow",
            name="first_air_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
